version: '3'

services:
  expresso-macchiato:
    container_name: expresso-macchiato
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: always
    environment:
      - "MINIO_ROOT_USER=yourusername"
      - "MINIO_ROOT_PASSWORD=passatleast5char"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./your-local-volume:/data
